### ISSUE TITLE
Buffer time mismatch cause errors in timeline.

### ISSUE THREAD

**Issue by Vortexakhaj** [snylonue/mpv_slicing_copy#5] opened 2021-12-22 10:05 UTC
I think you have forgotten to include the buffer time of around 10 secs from the start of the clip to the end using FFmpeg. Which causes the sliced clip to go into a -ve time such as -00:00:06 and then it plays until 00:00:00 without audio and then speeds up to catch up with the playback time.

**Comment by snylonue** [comment] 2022-01-17 13:54
Please provide a log file and a sample file
I can't reproduce it

**Comment by jcrd** [comment] 2022-06-18 22:13
I experienced exactly this issue. The cut video would play back starting at a negative timestamp and upon reaching zero would lag for a moment, then speed up.

I am not very experienced with `ffmpeg` but adding the `-rtbufsize 16M` flag seems to resolve this. I choose *16M* arbitrarily. Perhaps this is related to hardware capabilities?

**Comment by snylonue** [comment] 2022-06-19 00:02
@jcrd can you upload a log file (made with `mpv --log-file=mpv.log` or `mpv -v -v`)?

**Comment by jcrd** [comment] 2022-06-19 01:41
I've attached the log file. I open a video, allow it to play for a few seconds, make `mpv` fullscreen, cut the video, and check the console to ensure it's finished before closing. The resulting cut video behaves as described above.

[mpv.log](https://github.com/snylonue/mpv_slicing_copy/files/8934600/mpv.log)

**Comment by snylonue** [comment] 2022-06-25 23:58
The minus timestamp is probably related to the video itself (the distance between the timestamp and the nearest I frame), and speeding-up is caused by a-v desync I think.
However, I'm lack of both time and experience to investigate it.
Since adding `-rtbufsize 16M` solves it, you can [set `ffmpeg_path=ffmpeg -rtbufsize 16M` in the config file](https://mpv.io/manual/master/#lua-scripting-on-update%5D%5D)).
Also change `vcodec` to a proper value may also help.

**Comment by snylonue** [comment] 2022-12-18 02:18
I have confirmed the issue lies in the requested timestamp is not the key frame and the script uses `-vcodec copy` to avoid re-encoding.

I would refactor the related part to (hopefully) deal with it.

**Closed as completed** 2023-11-27 12:58 UTC
Labels: enhancement, help wanted
